// <auto-generated />
using System;
using Infrastructure.Persistences.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.OutboxDb
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20230610145036_InitialOutBox")]
    partial class InitialOutBox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Outbox")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreateDate");

                    b.Property<int>("Hits")
                        .HasColumnType("integer")
                        .HasColumnName("Hits");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OriginalUrl");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ShortUrl");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShortUrl");

                    b.ToTable("Url", "Outbox");
                });
#pragma warning restore 612, 618
        }
    }
}
