// <auto-generated />
using System;
using Infrastructure.Persistences.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ShortUrlDbContext))]
    [Migration("20230611145133_CreateOutbox")]
    partial class CreateOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ShortUrl")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.OutBoxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<string>("Error")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Error");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("OccurredOn");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp")
                        .HasColumnName("ProcessedOn");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("OutBoxMessage", "ShortUrl");
                });

            modelBuilder.Entity("Domain.Entities.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreateDate");

                    b.Property<int>("Hits")
                        .HasColumnType("integer")
                        .HasColumnName("Hits");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OriginalUrl");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("ShortUrl");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShortUrl");

                    b.ToTable("Url", "ShortUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
